Added czech language
ClearSkyTeam/ClearSky pull request #695
Opened 2016-09-03 18:11 UTC by ondraczsk

not stable, needs fix links

2016-09-14 18:50 UTC, robske110 commented on README.md
> +# <a name="CZE"></a>Česky
seems to acually work

2016-09-14 18:50 UTC, robske110 commented on README.md
> +####  [Česky/Czech](#CZE)
please do not put this all the way up

2016-09-14 18:50 UTC, robske110 requested changes
Please check the following stuff:

2016-10-21 12:05 UTC, thebigsmileXD commented
updates?

2016-11-01 15:59 UTC, thebigsmileXD commented
Changes not applied

2016-11-01 15:59 UTC, closed without merging